---
title: "Tolstoy Analysis"
author: "Alex Salem"
date: 2018-06-12
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Loading libraries:
```{r}
library(readr)
library(tidytext)
library(tidyverse)
```

##Reading in data:
```{r}
anna_karenina<- read_csv("anna_karenina.csv", col_types = cols(title = col_factor(levels = NULL)))
boyhood <- read_csv("boyhood.csv", col_types = cols(title = col_factor(levels = NULL)))
childhood <- read_csv("childhood.csv", col_types = cols(title = col_factor(levels = NULL)))
cossacks <- read_csv("cossacks.csv", col_types = cols(title = col_factor(levels = NULL)))
resurrection<- read_csv("resurrection.csv", col_types = cols(title = col_factor(levels = NULL)))
war_and_peace<- read_csv("war_and_peace.csv", col_types = cols(title = col_factor(levels = NULL)))
youth<- read_csv("youth.csv", col_types = cols(title = col_factor(levels = NULL)))

anna_karenina <- anna_karenina %>% 
  rownames_to_column()

boyhood <- boyhood %>% 
  rownames_to_column()

childhood <- childhood %>% 
  rownames_to_column()

cossacks <- cossacks %>% 
  rownames_to_column()

resurrection <- resurrection %>% 
  rownames_to_column()

war_and_peace <- war_and_peace %>% 
  rownames_to_column()

youth <- youth %>% 
  rownames_to_column()


data <- bind_rows(childhood, anna_karenina, resurrection)
  #bind_rows(anna_karenina, boyhood, childhood, cossacks, resurrection, war_and_peace, youth)
#bind_rows(childhood, resurrection)
```
##Lollipop plot with different numbers of indicies:
```{r}
data_final<- data %>% 
  group_by(title) %>% 
  inner_join(get_sentiments("bing"), by = c("words" = "word")) %>% 
  count(title, index = as.numeric(rowname)%/%1500, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive/(positive +negative))
data_final

ggplot(data_final, aes(index, sentiment, color = title)) +
  geom_point(size = .5, show.legend = FALSE) +
  geom_hline(aes(yintercept=.5))+
  geom_segment(aes(x=index, xend = index, y = sentiment, yend = .5)) +
  facet_wrap(~title, ncol = 3, scales = "free_x")
```

##Lollipop plot with same number of indicies:
```{r}
data %>% 
  group_by(title) %>% 
  count(title, index = max(as.numeric(rowname)))

data_final<- data %>% 
  group_by(title) %>% 
  inner_join(get_sentiments("bing"), by = c("words" = "word")) %>% 
  count(title, index = as.numeric(rowname)%/%as.numeric(max(as.numeric(rowname)/50)), sentiment) %>%
  filter(as.numeric(index)!=50) %>% 
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive/(positive +negative))
data_final
```

```{r}
labels <- c(childhood = "Childhood, 1852", anna_karenina = "Anna Karenina, 1877", resurrection = "Resurrection, 1899")

data_final$title<- fct_relevel(data_final$title, "childhood", "anna_karenina", "resurrection")

ggplot(data_final, aes(index, sentiment, color =  title)) +
  geom_point(size = .5, show.legend = FALSE) +
  geom_hline(aes(yintercept=.5))+
  geom_segment(aes(x=index, xend = index, y = sentiment, yend = .5)) +
  scale_color_discrete(name = "Book", labels = labels) +
  facet_wrap(~title, ncol = 3, labeller = labeller(title = labels)) +
  ggtitle("Positive and Negative Sentiment across Tolstoy Novels") +
  theme(axis.title.x=element_blank()) +
  theme(axis.ticks.x=element_blank()) +
  theme(axis.text.x=element_blank()) +
  theme(legend.position = "bottom")
  
```

##Original bar charts:
```{r}
afinn_data <- data %>% 
  inner_join(get_sentiments("afinn"), by = c("words" = "word")) %>% 
  group_by(title, index = as.numeric(rowname) %/%1500) %>% 
  summarise(sentiment = sum(score))

get_sentiments("afinn")

afinn_data_2 <- data %>% 
  inner_join(get_sentiments("bing"), by = c("words" = "word")) %>%
  count(title, index = as.numeric(rowname) %/% 1000, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)

afinn_data_3 <- data %>% 
  inner_join(get_sentiments("bing"), by = c("words" = "word")) %>%
  count(title, index = as.numeric(rowname)%/%as.numeric(max(as.numeric(rowname)/50)), sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
```

```{r}
ggplot(afinn_data, aes(index, sentiment, fill = title)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~title, ncol = 3, scales = "free_x")


ggplot(afinn_data_2, aes(index, sentiment, fill = title)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  facet_wrap(~title, ncol = 3, scales = "free_x")+
  theme(axis.title.x=element_blank()) +
  theme(axis.ticks.x=element_blank()) +
  theme(axis.text.x=element_blank())

ggplot(afinn_data_3, aes(index, sentiment, fill = title)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  facet_wrap(~title, ncol = 3, scales = "free_x")
```


